### ISSUE TITLE
Invalid argument(s): No encoder to encode the value

### ISSUE THREAD

**Issue by alamboley** [a14n/dart-xmlrpc#10]
Hello,

Thank you for this library. I'm trying to connect to Odoo's API https://www.odoo.com/documentation/10.0/api_integration.html.

I was able to get the version, but when giving credentials access I get this issue from the plugin: `flutter: Invalid argument(s): No encoder to encode the value`.

```dart
import 'package:flutter/material.dart';
import 'package:xml_rpc/client.dart' as xml_rpc;
import 'package:xml_rpc/client.dart';

void main() {
  const url = 'https://my-url.com';

  xml_rpc
      .call(url + '/xmlrpc/2/common', 'version', [])
      .then((result) => {
            print(result),
            xml_rpc
                .call(url, 'authenticate', ['db-odoo', 'firstname.name', 'my-pwd', {}], encodeCodecs:standardCodecs, decodeCodecs: standardCodecs)
                .then((result) => print(result))
                .catchError((error) => print(error))
          })
      .catchError((error) => print(error));

  runApp(MyApp());
}
```

At first I didn't provide `encodeCodecs` and `decodeCodecs`, but adding them give me same error.

Do I've to create an encoder? If so, could you give me some clues?

Thanks

**Comment by a14n** [comment]
I'm not sure if the error comes from request or response as I can't test it.

The standard codecs support `Map<String, dynamic>` but not other maps so you perhaps have to use `['db-odoo', 'firstname.name', 'my-pwd', <String, dynamic>{}]` instead of `['db-odoo', 'firstname.name', 'my-pwd', {}]`.

Moreover you can use async/await to make the code easier to read.

```dart
  try {
    final versionResult =
        await xml_rpc.call(url + '/xmlrpc/2/common', 'version', []);
    print(versionResult);
    final authenticateResult = await xml_rpc
        .call(url, 'authenticate', ['db-odoo', 'firstname.name', 'my-pwd', <String, dynamic>{}]);
    print(authenticateResult);
  } catch (error) {
    print(error);
  }
```

**Comment by alamboley** [comment]
Hi @a14n thanks for the answer. Unfortunately moving to `<String, dynamic>{}` gave me an error 400 bad request.

If you provide me your mail, I can give you some credential. Thanks again!

**Comment by a14n** [comment]
If you now get a 400 it means that the request is well encoded and sent to the server. It seems to be an issue with the API usage of the remote service.

Sorry but I don't have the time to read the doc and try to make it works :-/

**Comment by alamboley** [comment]
No problem, got it! The authenticate url should also use `'/xmlrpc/2/common'`, it wasn't obvious in the doc. And `<String, dynamic>{}` did the trick 👍 

Thanks again for your help!
