### ISSUE TITLE
Flutter: Response string encoding 

### ISSUE THREAD

**Issue by alexvinidiktov** [a14n/dart-xmlrpc#12]
Hello, 

I'm having trouble getting correctly encoded response strings.

Tried both Flutter for Web and for macOS.

I'm on Flutter 1.21.0-1.0.pre • channel dev.

```
final url2 = 'https://app.vocabilis.com/test/public_call/xmlrpc';
final result = await xml_rpc.call(url2, 'foo', ['мир']);
print(result);
```

The result I'm getting is "Ð¼Ð¸Ñ baz".
The correct result should be "мир baz".

What am I missing?

**Comment by a14n** [comment]
By default _utf8_ encoding is used but you can provided something else with [the encoding named parameter](https://github.com/a14n/dart-xmlrpc/blob/51ffd676c761f5978a7c9c17f482f469ad1c46f2/lib/src/client.dart#L32)

**Comment by alexvinidiktov** [comment]
The server seems to be sending the result in utf8.

I assumed that the string "Ð¼Ð¸Ñ� baz" was encoded as utf8 by the server but not decoded properly by the client.

You can load the pure xml (non rpc) version here:
https://app.vocabilis.com/test/public_call/xml/foo?bar=привет

**Comment by a14n** [comment]
When you exchange xml_rpc datas both client and server have to use the same encoding. IIRC the spec does not specify an encoding.
