### ISSUE TITLE
Migrate the library to null safe version of dart

### ISSUE THREAD

**Issue by JohnnyVM** [a14n/dart-xmlrpc#13]
Hello.

> The library 'package:xml_rpc/client.dart' is legacy, and should not be imported into a null safe library. <br> Try migrating the imported library.

Is it expected that the library will migrate to a null safe version of Dart?
Regards

**Comment by a14n** [comment]
Migration is blocked by dart-lang/http#501

**Comment by JohnnyVM** [comment]
okay, thanks for your answer :) <br>
if you need help for migrating after unblock i can try to help you

**Comment by a14n** [comment]
I will let this issue open to track the progression.

**Comment by a14n** [comment]
Fixed by #14 and available in [0.4.0-nullsafety.0](https://pub.dev/packages/xml_rpc/versions/0.4.0-nullsafety.0)
