### ISSUE TITLE
How to create new codec for list of struct

### ISSUE THREAD

**Issue by bluespada** [a14n/dart-xmlrpc#16]
I have problem to create list of struct , can you tell how to create a new codec for that , i have already read the documentation but, i still have no idea about it.

**Comment by bluespada** [comment]
I miss understand how the codecs works , i am so sorry for create this issue :)

**Comment by a14n** [comment]
No problem. You're always free to ask questions if you don't understand something :) This misunderstanding may be because of bad documentation or API and it's always valuable as package author to have the feedback of users.
