### ISSUE TITLE
retry, cancel, timeout support?

### ISSUE THREAD

**Issue by akalitenya** [a14n/dart-xmlrpc#9]
Hi. 
How to set request timeout? retry logic? ability to cancel request?

**Comment by a14n** [comment]
Nothing like this is natively provided by this package.

But you can provide your own function to make the http post (and so implement what you want):

```dart
var result = await xml_rpc.call(url, 'someMethod', params, httpPost: myCustomPostThatDoRetryTimeoutOrCancel);
```
